database:
  use_DB: True
  read: True  
  write: True
  name: "box504"                                                                           # save your data in the database its nicer :)
  db_path: '/ceph/home/fillies/tmr_sensors/automatization/Databases/cube.db'           # Abs Path to database. Independent of individual Sim so needs to stay global
  postProc_global_path: '/ceph/home/fillies/tmr_sensors/automatization/Databases/cube' # Abs path to folder where plots of post proc will be saved also need to stay global                                

shape:
  name: "Box"           # Ellipse, Box     are so far supportet
  init_xlen: 0.12
  init_ylen: 0.07
  init_zlen: 0.14
  

simulation:
  sim_name: '2bu012022007017014024'
  iter: 2000000
  main_Mesh_min: 1e-4
  main_mesh_max: 1.0
  object_Mesh_max: 5e-3  # 5e-9
  xlen_start: 0.12
  xlen_stop: 0.22
  ylen_start: 0.07
  ylen_stop: 0.17
  zlen_start: 0.14
  zlen_stop: 0.24
  hstart: 0.5
  hfinal: -0.3
  hstep: -0.0001

optimizer:
  acq_kind: 'ucb'           # 'ei', 'ucb', 'poi' supported
  kappa: 2.5                # 2.576
  xi: 0.0                   # 0.0
  kappa_decay: 1.0          # 1.0
  kappa_decay_delay: 0      # 0

server:
  number_cores: 4
  mem_GB: 20
  gpu: 'nv12'                # nv12, nv16, nv32 B4vex only Salome is currently on CPU

generalSettings:
  log_level: 2
  location: 'not_set'   # Do not set this here. This is set in the main script
