database:
  use_DB: False
  read: False  
  write: False
  name: "box504"                                                                           # save your data in the database its nicer :)
  db_path: '/ceph/home/fillies/tmr_sensors/automatization/Databases/cube.db'           # Abs Path to database. Independent of individual Sim so needs to stay global
  postProc_global_path: '/ceph/home/fillies/tmr_sensors/automatization/Databases/cube' # Abs path to folder where plots of post proc will be saved also need to stay global                                

shape:
  name: "Box"           # Ellipse, Box, Stick     are so far supportet
  init_xlen: 1.5
  init_ylen: 0.15
  init_zlen: 0.015
  

simulation:
  sim_name: 'gE100'
  iter: 100
  main_Mesh_min: 1e-4
  main_mesh_max: 1.0
  object_Mesh_max: 5e-3  # 5e-9
  xlen_start: 1
  xlen_stop: 2
  ylen_start: 0.1
  ylen_stop: 0.2
  zlen_start: 0.01
  zlen_stop: 0.02
  hstart: 0.5
  hfinal: -0.3
  hstep: -0.0001

optimizer:
  acq_kind: 'grid'           # 'ei', 'ucb', 'poi', 'rand' (random beanch mark test), 'grid' supported
  kappa: 0.0                # 2.576
  xi: 25.0                   # 0.0
  kappa_decay: 1.0          # 1.0
  kappa_decay_delay: 0      # 0

server:
  number_cores: 2
  mem_GB: 25
  gpu: 'nv12'                # nv12, nv16, nv32 B4vex only Salome is currently on CPU

generalSettings:
  log_level: 2
  location: 'not_set'   # Do not set this here. This is set in the main script
